version: '3.9'

services:
  pothole-detector:
    build: ./adas
    container_name: pothole-detector
    networks:
      - zenoh-net

  carla:
    build: ./carla-setup
    container_name: fake-publisher-carla
    networks:
      - zenoh-net

networks:
  zenoh-net:
    driver: bridge
