version: '3.9'

services:
  listener:
    build: ./python
    container_name: listener
    networks:
      - zenoh-net

  pothole-detector:
    build: ./ankaios/aaos
    container_name: app2
    networks:
      - zenoh-net

  carla:
    build: ./app3
    container_name: app3
    networks:
      - zenoh-net

networks:
  zenoh-net:
    driver: bridge
